doctrine:
    orm:
        mappings:
            Users:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/vendor/carguru/vendor-bundle/src/Users/Entity'
                prefix: 'Vendor\Users\Entity'
                alias: VendorUsers