doctrine:
    orm:
        mappings:
            CarguruVendorBundle:
                is_bundle: true
                type: attribute
                dir: '/Domain'
                prefix: 'Carguru\VendorBundle\Domain'